CREATE TABLE `RMAClaim`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`CustomerName` VARCHAR(40),
	`Email` VARCHAR(128),
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`OrderNumber` VARCHAR(12),
	`PhoneNumber` VARCHAR(24),
	`ProductName` VARCHAR(40),
	`RMAID` VARCHAR(24),
	`SerialNumber` VARCHAR(40),
	`SoftDeleteFlag` BOOLEAN,
	`Status` VARCHAR(40),
	PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
ALTER TABLE `RMAClaim`
	ADD CONSTRAINT `056bc8de9ae1303b0978db07371f0a` UNIQUE KEY(`id`),
	ADD CONSTRAINT `7d824dbd1cb156caddac49687b95d8` UNIQUE KEY(`RMAID`);
